export const MENU = [
{
	day:"monday",
	imgsrc:"../assets/images/chest.jpg",
	title:"CHEST"
},{
	day:"tuesday",
	imgsrc:"../assets/images/chest.jpg",
	title:"CHEST"
},{
	day:"wednesday",
	imgsrc:"../assets/images/chest.jpg",
	title:"CHEST"
},{
	day:"thursday",
	imgsrc:"../assets/images/chest.jpg",
	title:"CHEST"
},{
	day:"friday",
	imgsrc:"../assets/images/chest.jpg",
	title:"CHEST"
},{
	day:"saturday",
	imgsrc:"../assets/images/chest.jpg",
	title:"CHEST"
}]